In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('Downloads/mobile_feature.csv')

In [31]:
df['user_id'].isna().sum()

np.int64(2)

In [33]:
df['user_id'].dtype

dtype('float64')

In [8]:
df.head(10)

,timestamp,user_id,session_id,ip_address,device_os,device_os_version,device_model,screen_resolution,location_country,location_city,...,memory_usage_mb,event_type,event_target,event_value,app_version,session_duration_sec,is_subscribed,user_age,push_enabled,event_date
0,2025-01-13T23:12:43,13457.0,S-852694,181.246.29.95,Android,9.9,OnePlus 9,1080x1920,Senegal,South Luiston,...,3687,double_tap,profile_image,5,2.6.8,3311,True,51,False,13-01-2025
1,2024-12-24T22:57:29,95977.0,S-766538,59.155.205.42,Android,7.9,Samsung Galaxy S22,1080x1920,Greenland,Lake Brandonton,...,3521,pinch,search_bar,6,3.3.6,3283,False,40,False,24-12-2024
2,2024-12-22T09:00:26,52758.0,S-228244,183.205.124.1,iOS,15.1,iPhone 13,1080x1920,Falkland Islands (Malvinas),Julieside,...,639,zoom,menu_icon,6,5.4.5,2870,True,73,True,22-12-2024
3,2025-01-07T02:53:07,53777.0,S-633216,179.124.111.38,iOS,16.1,iPhone 14 Pro,720x1280,Comoros,North Steven,...,119,long_press,checkout_button,9,4.7.1,332,True,47,False,07-01-2025
4,2024-12-22T15:58:18,6302.0,S-508537,198.184.172.85,Android,7.6,Motorola Edge,1080x1920,Mayotte,Ernestport,...,1789,view,settings_button,7,2.0.8,1694,True,32,False,22-12-2024
5,2025-01-04T11:25:33,32032.0,S-445295,180.41.133.196,Android,13.8,Samsung Galaxy Note20,1080x1920,Senegal,Port Angela,...,2042,long_press,checkout_button,8,3.0.0,3446,False,77,True,04-01-2025
6,2025-01-02T19:17:13,88775.0,S-995611,63.61.79.118,Android,7.2,Samsung Galaxy S22,1440x2560,France,Kellychester,...,672,share,home_page_banner,2,3.3.2,699,True,47,False,02-01-2025
7,2025-01-03T01:02:23,65515.0,S-639814,131.121.116.90,Android,7.2,Samsung Galaxy S22,2160x3840,Saint Lucia,New Ashleychester,...,2112,zoom,menu_icon,7,2.4.8,2232,True,37,False,03-01-2025
8,2025-01-01T18:18:20,4782.0,S-500767,205.118.155.209,iOS,13.9,iPhone SE (2022),1440x2560,Montenegro,New Michelletown,...,4319,view,search_bar,8,4.6.7,2332,True,68,True,01-01-2025
9,2025-01-11T15:50:15,67787.0,S-895407,173.44.76.233,iOS,12.2,iPhone 12,1080x1920,Saint Martin,Robinsonmouth,...,505,swipe,home_page_banner,3,2.3.9,2250,False,72,False,11-01-2025

In [11]:
df.tail()

,timestamp,user_id,session_id,ip_address,device_os,device_os_version,device_model,screen_resolution,location_country,location_city,...,memory_usage_mb,event_type,event_target,event_value,app_version,session_duration_sec,is_subscribed,user_age,push_enabled,event_date
92000,2024-12-23T03:45:30,70305.0,S-813151,84.87.238.194,Android,7.7,Samsung Galaxy S22,1440x2560,Western Sahara,Nelsonton,...,852,double_tap,notification_popup,8,5.3.3,334,True,29,True,23-12-2024
92001,2024-12-22T12:03:25,44090.0,S-426764,146.222.70.16,Android,11.8,Motorola Edge,1536x2048,Germany,New Dawn,...,2784,like,search_bar,3,1.2.1,2422,False,68,True,22-12-2024
92002,2024-12-29T04:37:40,25958.0,S-520236,163.148.157.231,Android,8.6,Motorola Edge,1080x1920,Monaco,Jennahaven,...,3280,share,search_bar,10,3.4.6,2752,False,21,True,29-12-2024
92003,2024-12-17T15:47:38,67802.0,S-593427,120.215.26.176,Android,13.2,Google Pixel 6,1080x1920,Palau,Paulville,...,4022,scroll,post_video,5,1.4.1,1449,False,78,False,17-12-2024
92004,2024-12-20T13:35:29,50716.0,S-327451,79.200.50.27,iOS,15.9,iPhone SE (2022),1440x2560,Kyrgyz Republic,Port Christopherberg,...,2829,click,post_video,4,1.2.1,912,False,57,True,20-12-2024

In [10]:
df.shape

(92005, 23)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 92005 entries, 0 to 92004
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             92005 non-null  str
 1   user_id               92003 non-null  float64
 2   session_id            92005 non-null  str
 3   ip_address            92005 non-null  str
 4   device_os             92005 non-null  str
 5   device_os_version     92005 non-null  float64
 6   device_model          92005 non-null  str
 7   screen_resolution     92005 non-null  str
 8   location_country      92005 non-null  str
 9   location_city         92005 non-null  str
 10  app_language          92005 non-null  str
 11  network_type          92005 non-null  str
 12  battery_level         92005 non-null  int64
 13  memory_usage_mb       92005 non-null  int64
 14  event_type            92005 non-null  str
 15  event_target          92005 non-null  str
 16  event_value           92005 non-null  int64
 17  app_version           92005 non-null  str
 18  session_duration_sec  92005 non-null  int64
 19  is_subscribed         92005 non-null  bool
 20  user_age              92005 non-null  int64
 21  push_enabled          92005 non-null  bool
 22  event_date            92005 non-null  str
dtypes: bool(2), float64(2), int64(5), str(14)
memory usage: 26.2 MB

In [40]:
df.columns.tolist()

['timestamp',
 'user_id',
 'session_id',
 'ip_address',
 'device_os',
 'device_os_version',
 'device_model',
 'screen_resolution',
 'location_country',
 'location_city',
 'app_language',
 'network_type',
 'battery_level',
 'memory_usage_mb',
 'event_type',
 'event_target',
 'event_value',
 'app_version',
 'session_duration_sec',
 'is_subscribed',
 'user_age',
 'push_enabled',
 'event_date']

In [15]:
# how many unique users are there
df['user_id'].nunique()

59805

In [30]:
df['user_id'].value_counts()

user_id
44686.0    7
27029.0    7
87543.0    7
60807.0    7
3734.0     7
          ..
98324.0    1
98777.0    1
88032.0    1
70305.0    1
44090.0    1
Name: count, Length: 59805, dtype: int64

In [17]:
# how many total sesssions are there
df['session_id'].nunique()

87475

In [19]:
# which event / feature is used most
df['event_target'].value_counts().head(10)

event_target
checkout_button       12013
post_video            11538
search_bar            11453
notification_popup    11444
home_page_banner      11413
profile_image         11405
menu_icon             11379
settings_button       11360
Name: count, dtype: int64

In [20]:
# which device os is used the most
df['device_os'].value_counts()

device_os
Android    52666
iOS        39339
Name: count, dtype: int64

In [21]:
# what is the average session duration
df['session_duration_sec'].mean()

np.float64(1806.3916961034727)

In [22]:
# how many subscribed and non-suscribed users are there
df['is_subscribed'].value_counts()

is_subscribed
False    46266
True     45739
Name: count, dtype: int64

In [24]:
# which app version is used most
df['app_version'].value_counts().head(10)

app_version
2.8.0    784
1.8.2    219
3.9.0    216
1.2.4    216
2.0.3    214
4.3.6    214
5.4.3    214
2.3.5    210
4.8.5    209
5.9.2    209
Name: count, dtype: int64

In [25]:
# how many users have push notification
df['push_enabled'].value_counts()

push_enabled
False    46137
True     45868
Name: count, dtype: int64

In [26]:
# which network type is most commonly used
df['network_type'].value_counts()

network_type
3G      23491
WiFi    22864
4G      22853
5G      22797
Name: count, dtype: int64

In [39]:
# which country has the highest number of users
df. groupby('location_country')['user_id'].nunique().sort_values(ascending=False).head(10)

location_country
Korea                    1061
Congo                     752
Uruguay                   419
Honduras                  413
El Salvador               410
Morocco                   410
Saint Kitts and Nevis     410
Serbia                    410
Niue                      408
Venezuela                 407
Name: user_id, dtype: int64

In [4]:
# what is the average battery level
df['battery_level'].mean()

np.float64(50.24512798217488)

In [5]:
# which event type occurs most frequently
df['event_type'].value_counts()

event_type
share         9655
click         9325
view          9219
swipe         9188
scroll        9153
long_press    9146
zoom          9123
double_tap    9092
like          9066
pinch         9038
Name: count, dtype: int64

In [6]:
# which  is the average memory usage
df['memory_usage_mb'].mean()

np.float64(2072.5580131514594)

In [7]:
# which age group has the highest number of users
df['user_age'].value_counts().sort_index()

user_age
0        1
1        1
2        2
5        1
9        1
      ...
77    1282
78    1356
79    1324
80    1346
89       1
Name: count, Length: 75, dtype: int64

In [8]:
# what is the average session duration by device os
df.groupby('device_os')['session_duration_sec'].mean().sort_values(ascending=False)

device_os
Android    1810.739016
iOS        1800.571621
Name: session_duration_sec, dtype: float64